// <auto-generated />
using LightsOut.Services.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Solvtio.Data.Migrations
{
    [DbContext(typeof(SolvtioDbContext))]
    [Migration("202006261125114_AutomaticMigration")] //202006261125114_AutomaticMigration 
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LightsOut.Services.Data.TableEntity.LightsOutSetting", b =>
                {
                    b.Property<string>("SettingName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SettingValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SettingName");

                    b.ToTable("LightsOutSetting");
                });
#pragma warning restore 612, 618
        }
    }
}
